{
	"version": 1672385304,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bckgrbricks.png",
		"images/bckgrtown.png",
		"images/metal-sheet0.png",
		"images/hero-sheet0.png",
		"images/hero-sheet1.png",
		"images/hero-sheet2.png",
		"images/platform-sheet0.png",
		"images/glass-sheet0.png",
		"images/potionlittle-sheet0.png",
		"images/spines-sheet0.png",
		"images/gemstone-sheet0.png",
		"images/heart-sheet0.png",
		"images/btc-sheet0.png",
		"images/hpicon-sheet0.png",
		"images/stone-sheet0.png",
		"images/potionbig-sheet0.png",
		"images/portal-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tilemap.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite6-sheet1.png",
		"images/sprite7-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/play-sheet0.png",
		"images/exit-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"media/прыжок.m4a",
		"media/прыжок.ogg",
		"media/сбор монет.m4a",
		"media/сбор монет.ogg",
		"media/сбор алмаза.m4a",
		"media/сбор алмаза.ogg",
		"media/зелье.m4a",
		"media/зелье.ogg",
		"media/конец жизней.m4a",
		"media/конец жизней.ogg",
		"media/щелчок шипы.m4a",
		"media/щелчок шипы.ogg",
		"media/женское ранение.m4a",
		"media/женское ранение.ogg",
		"media/телепорт.m4a",
		"media/телепорт.ogg",
		"media/меч.m4a",
		"media/меч.ogg",
		"media/desert theme.m4a",
		"media/desert theme.ogg",
		"media/босс.m4a",
		"media/босс.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}